### ISSUE TITLE
colony-js-adapter-ethers throws error with latest yarn

### ISSUE THREAD

**Issue by igorline** [JoinColony/colonyStarter#45] opened 2018-11-30 12:05 UTC
I'm getting this error with `@colony/colony-starter-basic@1.0.0-beta.6`

`error @colony/colony-js-adapter-ethers@1.7.0: The engine "yarn" is incompatible with this module. Expected version ">=1.3.2".
error Found incompatible module`

I'm using yarn 1.12.3

**Comment by ryanchristo** [comment] 2018-11-30 12:59
As mentioned in the Gitter channel, I was unable to reproduce using node `10.12` and yarn `1.12.3`. I created a PR to add the recommended yarn version to the docs. Let me know if a fresh setup works.

**Comment by chmanie** [comment] 2018-12-03 17:49
We really need to remove that line from colony-js. Pinging @JamesLefrere

**Comment by JamesLefrere** [comment] 2018-12-03 20:10
Fixed in colonyJS#316 👍 We'll make a new release so this can be resolved here.

**Comment by igorline** [comment] 2018-12-03 22:59
My bad! Seems like yarn wasn't linked to proper node version in nvm, thus there was this error thrown while setting up new project.
After installing -> linking yarn to proper node version everything is working smoothly!

**Comment by ryanchristo** [comment] 2018-12-04 04:49
@igorline No problem! Glad to hear everything is working now.

**Closed by ryanchristo** 2018-12-04 04:49 UTC
Labels: bug
