### ISSUE TITLE
Error seeding the network

### ISSUE THREAD

**Issue by mehranhydary** [JoinColony/colonyStarter#68] opened 2019-02-20 15:14 UTC
## Description

I am getting an error while trying to run the seed-network script.

## Steps to Reproduce

1. From the root directory of colony-starter-react run `yarn seed-network`

```
(node:98183) UnhandledPromiseRejectionWarning: Error: No such event "FundingPotAdded" on this contract
    at new ContractEvent (/Users/mehranhydary/Desktop/unicef/dev/colony/colony-starter-react/node_modules/@colony/colony-js-contract-client/lib/classes/ContractEvent.js:47:32)
    at ColonyClient.addEvent (/Users/mehranhydary/Desktop/unicef/dev/colony/colony-starter-react/node_modules/@colony/colony-js-contract-client/lib/classes/ContractClient.js:458:19)
    at ColonyClient.initializeContractMethods (/Users/mehranhydary/Desktop/unicef/dev/colony/colony-starter-react/node_modules/@colony/colony-js-client/lib/ColonyClient/index.js:662:12)
    at ColonyClient._callee$ (/Users/mehranhydary/Desktop/unicef/dev/colony/colony-starter-react/node_modules/@colony/colony-js-contract-client/lib/classes/ContractClient.js:142:22)
    at tryCatch (/Users/mehranhydary/Desktop/unicef/dev/colony/colony-starter-react/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/mehranhydary/Desktop/unicef/dev/colony/colony-starter-react/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/mehranhydary/Desktop/unicef/dev/colony/colony-starter-react/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/Users/mehranhydary/Desktop/unicef/dev/colony/colony-starter-react/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/mehranhydary/Desktop/unicef/dev/colony/colony-starter-react/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:98183) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:98183) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ryanchristo** [comment] 2019-02-20 16:55
Hey @mehranhydary!

I'm just going to repost the cause of the issue that we discussed in the [Gitter channel](https://gitter.im/JoinColony/colonyStarter).

I thought I set specific versions in the colonyStarter packages for colonyJS dependencies but it looks like I might have changed that recently. The issues are related to installing a couple colonyJS packages that are version `1.11.0`, which introduce some breaking changes and the colonyStarter packages have not been updated to the latest colonyJS packages yet. I started working on this yesterday and should have this fixed by the end of the day or sometime tomorrow.

In the meantime, make sure you are using `colony-js-client@1.10.0`.

**Comment by pynchmeister** [comment] 2019-03-06 15:13
Is this fixed? I am still having issues running ```yarn seed-network``` as well as ```yarn start``` (although this is probably due to the latter.

**Comment by ryanchristo** [comment] 2019-03-06 15:28
A new version has not been published yet so the same temporary solution is still required:

> In the meantime, make sure you are using colony-js-client@1.10.0.

**Comment by pynchmeister** [comment] 2019-03-07 17:03
Could you give more detail on how to verify I am using that version?

**Comment by igorline** [comment] 2019-03-07 17:07
> Could you give more detail on how to verify I am using that version?

Pin it in package.json explicitly

**Comment by ryanchristo** [comment] 2019-03-11 10:44
Hey @pynchmeister! Did you get it working? Just to clarify what that would look like, you would want the colonyJS packages in your`package.json` to look like this:

```
    "@colony/colony-js-client": "1.10.0",
    "@colony/colony-js-contract-loader-http": "1.10.0",
```

And then you would need to run `yarn` again to update the packages. I should be able to finish the updates and publish a new `colony-starter-react` package by the end of the day today, so this will no longer be an issue with a fresh install.

Sorry for the delay! I was at ETHCC and ETHParis last week!

**Comment by ryanchristo** [comment] 2019-03-22 08:53
Updated versions of `colony-starter-react` and `colony-starter-angular` published. Closing Issue.

**Closed by ryanchristo** 2019-03-22 08:53 UTC
Labels: bug
