### ISSUE TITLE
Include instructions for Docker

### ISSUE THREAD

**Issue by fuguefoundation** [JoinColony/colonyStarter#50] opened 2018-12-16 11:05 UTC
## Description

The repo mentions Docker as a dependency but makes no reference as to how it should be configured.

## Steps to Reproduce

I have followed the instructions both in `colony-starter-basic` and in the colony [Getting Started](https://docs.colony.io/colonyjs/docs-get-started/) docs. Each time I issue either of the following commands, I get a Docker error.

### Error
`Error: No such image: ethereum/solc:0.4.23`
`Error: Please pull 0.4.23 from docker before trying to compile with it.`

### Commands issued for this error (as specified in docs)
`yarn deploy-contracts` and
`./node_modules/.bin/truffle migrate --reset --compile-all`

I am still wrapping my head around Docker (which I have installed and it is running), so I imagine its role here has some implicit steps. But myself and others would benefit from a few helper steps in either the docs or this repo as to troubleshooting on this dependency. I'll make the pull request myself if I figure it out.

**Comment by chmanie** [comment] 2018-12-16 11:14
Good call! Docker is now a dependency of truffle (since v5) and certainly doesn’t mitigate the entry barrier here.
To fix your issue:

1) have docker installed and running 
2) in your command line do `docker pull ethereum/solc:0.4.23`

Then try again. You’re right, this should be part of the documentation (we’re happy about every PR :wink:)

**Comment by ryanchristo** [comment] 2018-12-17 03:39
@fuguefoundation Thanks for posting the issue!

Could you please confirm that it did not work when installing `colony-starter-basic`? Was Docker running when you ran the command? I just want to double check the issue because the `pull docker` command is included [here](https://github.com/JoinColony/colonyStarter/blob/38f357f72346d5a5ba41f62f3887cd4dae4852a8/packages/colony-starter-basic/scripts/initialize_project.sh#L21) in the initialization script of `colony-starter-basic`.

Either way, yes, "have docker installed and running" should be included in colonyStarter and this plus `docker pull` should be included in the colonyJS Get Started documentation.

**Comment by fuguefoundation** [comment] 2018-12-22 08:01
So before `yarn deploy-contracts`, I called `docker pull ethereum/solc:0.4.23` as mentioned above. Start Docker daemon, `docker login`, good to go.

What I think the confusion here is that these Readme instructions don't tell you to call `yarn initialize`, thus `initialize_project.sh` (which has the docker pull command in it) is not implemented unless you know to look for it explicitly.

I should also add that the instructions here vice the instructions in [Colony Docs](https://docs.colony.io/colonyjs/docs-get-started/) Getting Started section are sufficiently different *on the surface* so as to be confusing to newcomers (ie, employing shell scripts via package.json vs. copying commands with detailed truffle parameters into a terminal). To BUIDL a dApp is already a challenge, let alone digging into complex frameworks like Colony and troubleshooting Docker/other requirements. I write this as someone who is not new to this space. Suggest an effort to standardize your starter kit. I will continue to wrap my head around Colony in the coming weeks and hope to make a meaningful contribution to the project in the new year.

**Comment by ryanchristo** [comment] 2018-12-24 11:07
@fuguefoundation Thanks for the feedback! We are excited to have you buidling with us! 🎉 

`yarn initialize` is not included in the `colony-starter-basic` or `colony-starter-react` instructions because `yarn initialize` is called [here](https://github.com/JoinColony/colonyStarter/blob/89aa452900f748cec5e87db98bc3c73e5786dc66/packages/colony-starter/index.js#L101) when you install a package using the global `colony-starter` command (for example, `colony-starter colony-starter-basic`). Not sure why you would need to call `yarn initialize` unless you skipped step 1 and installed the package manually. 🤔 

The "Get Started" and "Colony Starter Basic" instructions are a bit different, this is true. The idea is to simplify the commands by moving the commands you see in the "Get Started" documentation to script files in the `colony-starter-basic` package.

For example, instead of running the following line of code as instructed in "Get Started":

```
./node_modules/.bin/truffle migrate --reset --compile-all
```

You would run `yarn deploy-contracts`, which runs the `deploy_contracts.sh` script:

```
#!/bin/bash

# Move to colonyNetwork directory
cd src/lib/colonyNetwork

# Compile and deploy colonyNetwork contracts
./node_modules/.bin/truffle migrate --compile-all --reset
```

The idea was to make it easier but looks like it might be a bit confusing. I will revisit the idea and try to make it easier or provide more explanation. I hope this explanation helps in the meantime!

Let us know if there are any other issues you are coming across. Feedback is always welcome!

**Comment by fuguefoundation** [comment] 2019-01-05 10:59
https://build.colony.io/t/ng-colony-truffle-box-for-colony-basic-starter-and-angular/129
@ryanchristo @chmanie 
Happy New Year! A Truffle Box I'm working on with Angular and Colony. Your feedback is welcome.

**Comment by dimitri0101** [comment] 2019-04-15 15:53
This is still an issue when installing via `npx -p @colony/colony-cli colony build colony-starter-react`

**Comment by ryanchristo** [comment] 2019-04-16 09:08
Hey @dimitri0101.

What is still an issue? Do you have docker installed and running? Can you share the error message?

**Comment by dimitri0101** [comment] 2019-04-17 16:55
I had to run `docker pull ethereum/solc:0.4.23` to get it to work. Sorry, maybe this is expected behavior?

**Comment by ryanchristo** [comment] 2019-04-18 07:30
No worries. You are right. The `docker pull ethereum/solc:0.4.23` is done within the `postinstall.sh` script and `npx` is running a script without installing the `colony-cli` package, so this step needs to be added to the readme instructions for "Using NPX".

In the near future, this will be included in the scripts for colonyNetwork but I will go ahead and add it to the readme in the meantime. Thanks for reporting this!

**Closed** 2019-04-18 13:33 UTC
Labels: documentation
